### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Cliffart44** [netology-code/guides#26]
Находится [вот здесь](https://github.com/netology-code/guides/blob/master/git-terminal/git-terminal.md#%D0%BA%D0%BE%D1%80%D0%BE%D1%82%D0%BA%D0%B8%D0%B9-%D0%BF%D1%83%D1%82%D1%8C), выделена ниже:

"Но есть способ короче. Если _**плностью**_ набрать имя следующей директории и нажать 2 раза клавишу TAB мы сможем заглянуть внутрь этой директории не прерывая команду."

**Comment by solarrust** [comment]
Присылайте Pull Request'ы с правками =)
И материалы станут лучше и вы потренируетесь ☺️

**Comment by Cliffart44** [comment]
Хорошо - как только дойду до них (пока ещё не умею 🧐)
